apiVersion: "kubeflow.org/v1alpha2"
kind: "TFJob"
metadata:
  name: "dist-recurrent-network"
spec:
  tfReplicaSpecs:
    PS:
      replicas: 2
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: tensorflow
              image: hanacolor/tf-dist-recurrent-network:1.0
              imagePullPolicy: Always
    Worker:
      replicas: 2
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: tensorflow
              image: hanacolor/tf-dist-recurrent-network:1.0
              imagePullPolicy: Always